# Generated by Django 4.2.6 on 2023-12-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_article_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
