# Generated by Django 4.2.6 on 2023-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=300)),
                ('img_alt', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('health', 'Health & Wellness'), ('fashion', 'Fashion & Beauty'), ('food', 'Food & Cooking'), ('lifestyle', 'Lifestyle'), ('finance', 'Finance & Business'), ('arts', 'Arts & Entertainment'), ('education', 'Education'), ('science', 'Science & Nature')], default='NULL', max_length=100)),
                ('sub_category', models.CharField(choices=[('Programming', 'Programming'), ('Web Development', 'Web Development'), ('Mobile Apps', 'Mobile Apps'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Cybersecurity', 'Cybersecurity'), ('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Mental Health', 'Mental Health'), ('Yoga & Meditation', 'Yoga & Meditation'), ('Healthy Living', 'Healthy Living'), ('Destination Guides', 'Destination Guides'), ('Travel Tips', 'Travel Tips'), ('Adventure Travel', 'Adventure Travel'), ('Backpacking', 'Backpacking'), ('Solo Travel', 'Solo Travel'), ('Fashion Trends', 'Fashion Trends'), ('Beauty Tips', 'Beauty Tips'), ('Makeup Tutorials', 'Makeup Tutorials'), ('Clothing Styles', 'Clothing Styles'), ('Accessories', 'Accessories'), ('Recipes', 'Recipes'), ('Cooking Tips', 'Cooking Tips'), ('Restaurant Reviews', 'Restaurant Reviews'), ('Healthy Eating', 'Healthy Eating'), ('International Cuisine', 'International Cuisine'), ('Personal Development', 'Personal Development'), ('Productivity', 'Productivity'), ('Relationships', 'Relationships'), ('Self-Care', 'Self-Care'), ('Home & Decor', 'Home & Decor'), ('Personal Finance', 'Personal Finance'), ('Investing', 'Investing'), ('Entrepreneurship', 'Entrepreneurship'), ('Marketing', 'Marketing'), ('Career Development', 'Career Development'), ('Movie Reviews', 'Movie Reviews'), ('Book Recommendations', 'Book Recommendations'), ('Music & Concerts', 'Music & Concerts'), ('Art & Design', 'Art & Design'), ('Theater & Performance', 'Theater & Performance'), ('Learning Strategies', 'Learning Strategies'), ('Educational Technology', 'Educational Technology'), ('Study Tips', 'Study Tips'), ('Online Courses', 'Online Courses'), ('Career Advice', 'Career Advice'), ('Astronomy', 'Astronomy'), ('Biology', 'Biology'), ('Environmental Science', 'Environmental Science'), ('Physics', 'Physics')], default='NULL', max_length=100)),
                ('thumbnail', models.ImageField(upload_to='Article/thumbnails/')),
                ('short_description', models.TextField()),
                ('main_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
